name: pypsml2E
channels:
  - pyviz
  - conda-forge
  - defaults
dependencies:
  - numpy
  - matplotlib=3.1.0=py37h5429711_0
  - networkx=2.3=py_0
  - pandas=0.24.2=py37he6710b0_0
  - scikit-learn=0.21.2=py37hd81dba3_0
  - scipy=1.2.1=py37h7c811a0_0
  - seaborn=0.9.0=py37_0
  - statsmodels=0.10.0=py37hdd07704_0
  - sympy=1.4=py37_0
  - theano=1.0.4=py37hf484d3e_1000
  - xlrd=1.2.0=py37_0
  - xlwt=1.3.0=py37_0
  - cvxpy>=1.0.24
  - pip:
    - pandas-datareader==0.7.0
